### ISSUE TITLE
Save Event button loses text

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#168]
When creating an event, if you leave the candidate blank, the Save Event button loses its text, so its just a black box.

![capture d ecran 2016-05-21 a 9 12 12 am](https://cloud.githubusercontent.com/assets/12802756/15449503/6bd6ead8-1f34-11e6-80a7-12a17ea58a2d.png)

**Comment by virajmahesh** [comment]
This should be fixed now!
On a side note, I'm getting notification emails pretty fast. Let me know if it's the same for you.

**Comment by mplauche** [comment]
still getting this problem - it looks like the menu text disappears too (i'm using safari, by the way).
![capture d ecran 2016-05-21 a 1 25 33 pm](https://cloud.githubusercontent.com/assets/12802756/15450701/9b34df1a-1f57-11e6-858c-57d497b59bc1.png)

**Comment by virajmahesh** [comment]
Sorry, it got stuck while deploying. Check it out now.

**Comment by mplauche** [comment]
it works!  but menu text disappears for some reason. 
![capture d ecran 2016-05-21 a 1 27 46 pm](https://cloud.githubusercontent.com/assets/12802756/15450709/e49d8e18-1f57-11e6-8830-009a787b9b19.png)

**Comment by mplauche** [comment]
yes - email notifications, including reset password, are super speedy right now!

**Comment by virajmahesh** [comment]
The menu text disappearing is unrelated, and it's only popping up in Safari. I'm going to have to do more digging to figure out how to fix it. Can we mark this issue as resolved, and open a new open to track the Safari menu bug?
